version: 0.2

phases:
  build:
    commands:
      - echo Starting build spring app
      - mvn clean package
  post_build:
    commands:
      - echo Spring Build completed successfully
artifacts:
  files:
    - target/ecom-shop.jar
  discard-paths: yes


server: